'use strict';
// Pointer operations work in the timezone displayed by the calendar.
let gesture=null,suppressClick=false,frame=0;
const calendarRoot=$('calendars');
function wallTime(day,minute){const d=dateAt(day);d.setUTCMinutes(minute);return instant(d.toISOString().slice(0,16))}
function hitTime(g,x,y){const columns=[...g.sc.querySelectorAll('.day-column')];let day=columns.findIndex(c=>{const r=c.getBoundingClientRect();return x>=r.left&&x<r.right});if(day<0)day=x<columns[0].getBoundingClientRect().left?0:6;const rect=columns[day].getBoundingClientRect();let minute=Math.max(0,Math.min(1440,Math.round((y-rect.top)/rect.height*1440)));return {day,minute,time:wallTime(day,minute)}}
function proposal(g,point){if(!Number.isFinite(point.time))return null;let start,end;if(g.mode==='create'){start=Math.min(g.anchor,point.time);end=Math.max(g.anchor,point.time);if(start===end)end=start+15*60000}else if(g.mode==='move'){start=g.original.start+(point.time-g.anchor);end=start+(g.original.end-g.original.start)}else if(g.mode==='start'){start=Math.min(point.time,g.original.end-60000);end=g.original.end}else{start=g.original.start;end=Math.max(point.time,g.original.start+60000)}return {start,end,state:g.state}}
function clearPreview(){calendarRoot.querySelectorAll('.drag-preview').forEach(e=>e.remove())}
function showPreview(g,r){clearPreview();if(!r){msg('That local time is skipped by daylight saving.');return}g.sc.querySelectorAll('.day-column').forEach((col,day)=>{let begin=wallTime(day,0),end=wallTime(day+1,0);if(r.end<=begin||r.start>=end)return;let a=Math.max(begin,r.start),b=Math.min(end,r.end),pa=parts(a),pb=parts(b),top=a===begin?0:Number(pa.hour)*60+Number(pa.minute),bottom=b===end?1440:Number(pb.hour)*60+Number(pb.minute);let preview=element('div','range drag-preview '+r.state,labels[r.state]+' '+pa.hour+':'+pa.minute+'–'+(b===end?'24:00':pb.hour+':'+pb.minute));preview.style.top=top/60*36+'px';preview.style.height=Math.max(4,(bottom-top)/60*36)+'px';col.append(preview)});msg(labels[r.state]+' · '+local(r.start).replace('T',' ')+' → '+local(r.end).replace('T',' ')+' · Release to apply')}
function updateGesture(){if(!gesture)return;const g=gesture;if(!g.moved)return;g.result=proposal(g,hitTime(g,g.x,g.y));showPreview(g,g.result)}
function autoScroll(){if(!gesture)return;const g=gesture,r=g.sc.getBoundingClientRect();if(g.moved){let delta=g.y<r.top+48?-7:g.y>r.bottom-30?7:0;if(delta){g.sc.scrollTop+=delta;updateGesture()}}frame=requestAnimationFrame(autoScroll)}
calendarRoot.addEventListener('pointerdown',e=>{suppressClick=false;if(e.button!==0||gesture)return;const col=e.target.closest('.day-column'),card=e.target.closest('.card');if(!col||!card?.classList.contains('editing'))return;const sc=card.querySelector('.scroll'),block=e.target.closest('button.range'),day=[...sc.querySelectorAll('.day-column')].indexOf(col);let original=null,index=null,mode='create';if(block){let begin=wallTime(day,0),end=wallTime(day+1,0),visible=own(selected).ranges.map((r,index)=>({r,index})).filter(({r})=>r.end>begin&&r.start<end),item=visible[[...col.querySelectorAll('button.range')].indexOf(block)];if(!item)return;original={...item.r};index=item.index;const rect=block.getBoundingClientRect(),edge=Math.min(8,rect.height/3);mode=e.clientY-rect.top<edge&&original.start>=begin?'start':rect.bottom-e.clientY<edge&&original.end<=end?'end':'move'}
let g={sc,mode,original,index,state:original?.state||$('availability').value,x:e.clientX,y:e.clientY,downX:e.clientX,downY:e.clientY,pointerId:e.pointerId,moved:false};g.anchor=hitTime(g,g.x,g.y).time;if(!Number.isFinite(g.anchor))return;gesture=g;sc.setPointerCapture(e.pointerId);if(!block)e.preventDefault();frame=requestAnimationFrame(autoScroll)});
calendarRoot.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.pointerId)return;gesture.x=e.clientX;gesture.y=e.clientY;if(Math.hypot(e.clientX-gesture.downX,e.clientY-gesture.downY)>3)gesture.moved=true;if(gesture.moved){e.preventDefault();document.body.classList.add('calendar-dragging');updateGesture()}});
function finishGesture(cancel=false){if(!gesture)return;const g=gesture;gesture=null;cancelAnimationFrame(frame);clearPreview();document.body.classList.remove('calendar-dragging');if(g.sc.hasPointerCapture(g.pointerId))g.sc.releasePointerCapture(g.pointerId);if(cancel){suppressClick=true;msg('Drag cancelled.');return}if(!g.moved&&g.original){edit(g.original,g.index);suppressClick=true;return}const r=g.result||proposal(g,hitTime(g,g.x,g.y));suppressClick=true;if(!r)return;let d=draft(),out=[];d.ranges.forEach((old,index)=>{if(index===g.index)return;if(old.end<=r.start||old.start>=r.end)out.push(old);else{if(old.start<r.start)out.push({...old,end:r.start});if(old.end>r.end)out.push({...old,start:r.end})}});out.push(r);d.ranges=out.sort((a,b)=>a.start-b.start);resetEdit();$('start').value=local(r.start);$('end').value=local(r.end);persist();render();msg('Time '+(g.mode==='create'?'added':g.mode==='move'?'moved':'resized')+'. Save via GitHub to share your changes.')}
calendarRoot.addEventListener('pointerup',e=>{if(gesture&&e.pointerId===gesture.pointerId)finishGesture()});calendarRoot.addEventListener('pointercancel',()=>finishGesture(true));calendarRoot.addEventListener('lostpointercapture',()=>{if(gesture)finishGesture(true)});calendarRoot.addEventListener('click',e=>{if(suppressClick&&e.detail!==0){e.preventDefault();e.stopImmediatePropagation();suppressClick=false}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&gesture){e.preventDefault();finishGesture(true)}});window.addEventListener('blur',()=>finishGesture(true));
