'use strict';
const REPO='abrahamalcuin/team-call-planner',KEY='team-time-ranges-v1',$=id=>document.getElementById(id),labels={free:'Free',maybe:'Maybe',busy:'Unavailable'};
let prefs={};try{prefs=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
let zone=prefs.zone||Intl.DateTimeFormat().resolvedOptions().timeZone,selected=Number(prefs.member)||0,drafts=prefs.drafts||{},records=Array.from({length:4},()=>({name:'',ranges:[],owner:''})),monday,loading=false,editIndex=null;
function persist(){localStorage.setItem(KEY,JSON.stringify({zone,member:selected,drafts}))}
function parts(t){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(t)).map(p=>[p.type,p.value]))}
function local(t){let p=parts(t);return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
function instant(v){if(!v)return NaN;let guess=Date.parse(v+'Z'),t=guess;if(!Number.isFinite(t))return NaN;for(let n=0;n<4;n++)t+=guess-Date.parse(local(t)+':00Z');return local(t)===v?t:NaN}
function currentMonday(){let d=new Date(local(Date.now()).slice(0,10)+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d}
function dateAt(n){return new Date(+monday+n*86400000)}
function own(i){return drafts[i]||records[i]}
function draft(){return drafts[selected]||(drafts[selected]={name:records[selected].name,ranges:records[selected].ranges.map(r=>({...r}))})}
function msg(s){$('status').textContent=s}
function element(tag,cls,text){let e=document.createElement(tag);e.className=cls||'';if(text)e.textContent=text;return e}
function resetEdit(){editIndex=null;$('addRange').textContent='Add time'}
function edit(r,index){editIndex=index;$('start').value=local(r.start);$('end').value=local(r.end);$('availability').value=r.state;$('addRange').textContent='Update time';$('start').focus()}
const zones=Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):['Asia/Manila','America/New_York','America/Los_Angeles','Europe/London'];
for(const z of new Set(['UTC',zone,...zones]))$('timezone').add(new Option(z.replaceAll('_',' '),z));$('timezone').value=zone;$('member').value=selected;
function render(){
 const fmt=new Intl.DateTimeFormat('en',{month:'short',day:'numeric',timeZone:'UTC'});$('weekLabel').textContent=fmt.format(monday)+' – '+fmt.format(dateAt(6))+' '+dateAt(6).getUTCFullYear();$('name').value=own(selected).name||'';for(let i=0;i<4;i++)$('member').options[i].textContent=own(i).name||`Person ${i+1}`;
 const root=$('calendars'),scrolls=[...root.querySelectorAll('.scroll')].map(x=>[x.scrollTop,x.scrollLeft]);root.replaceChildren();
 for(let i=0;i<4;i++){
 let card=element('section','card'+(selected===i?' editing':'')),head=element('div','card-head'),person=element('div','person');person.append(element('span','avatar',String(i+1)),document.createTextNode(own(i).name||`Person ${i+1}`),element('span','meta',records[i].owner?'@'+records[i].owner:'Unclaimed calendar'));head.append(person,element('span','badge',selected===i?(drafts[i]?'Editing · unsaved draft':'Editing'):'View only'));card.append(head);
 let sc=element('div','scroll'),grid=element('div','timeline');grid.append(element('div','corner','Time'));for(let day=0;day<7;day++)grid.append(element('div','day',new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(dateAt(day))));let axis=element('div','axis');for(let h=0;h<24;h++){let t=element('span','',String(h).padStart(2,'0')+':00');t.style.top=h*36+'px';axis.append(t)}grid.append(axis);
 for(let day=0;day<7;day++){let col=element('div','day-column'),date=dateAt(day).toISOString().slice(0,10),start=instant(date+'T00:00'),end=instant(dateAt(day+1).toISOString().slice(0,10)+'T00:00');
 own(i).ranges.forEach((r,index)=>{if(r.end<=start||r.start>=end)return;let a=Math.max(start,r.start),b=Math.min(end,r.end),pa=parts(a),pb=parts(b),top=a===start?0:Number(pa.hour)*60+Number(pa.minute),bottom=b===end?1440:Number(pb.hour)*60+Number(pb.minute);if(bottom<=top)bottom=top+Math.max(1,(b-a)/60000);let block=element('button','range '+r.state,labels[r.state]+' '+pa.hour+':'+pa.minute+'–'+(b===end?'24:00':pb.hour+':'+pb.minute));block.style.top=top/60*36+'px';block.style.height=Math.max(4,(bottom-top)/60*36)+'px';block.disabled=i!==selected;block.title=labels[r.state]+' · '+local(r.start).replace('T',' ')+' → '+local(r.end).replace('T',' ')+' '+zone;block.setAttribute('aria-label',block.title);block.onclick=()=>edit(r,index);col.append(block)});grid.append(col)}
 sc.append(grid);card.append(sc);root.append(card);sc.scrollTop=scrolls[i]?.[0]??252;sc.scrollLeft=scrolls[i]?.[1]??0;
 }
 let list=$('rangeList');list.replaceChildren();own(selected).ranges.forEach((r,index)=>{let row=element('div','range-row'),text=element('span','',labels[r.state]+' · '+local(r.start).replace('T',' ')+' → '+local(r.end).replace('T',' ')),editButton=element('button','','Edit'),del=element('button','','Remove');editButton.onclick=()=>edit(r,index);del.onclick=()=>{draft().ranges.splice(index,1);resetEdit();persist();render()};row.append(element('span','dot '+r.state),text,editButton,del);list.append(row)});
}
$('rangeForm').onsubmit=e=>{e.preventDefault();let start=instant($('start').value),end=instant($('end').value);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start){msg('Choose a valid start and a later end. Times skipped by daylight saving are not valid.');return}let d=draft(),out=[];d.ranges.forEach((r,index)=>{if(index===editIndex)return;if(r.end<=start||r.start>=end)out.push(r);else{if(r.start<start)out.push({...r,end:start});if(r.end>end)out.push({...r,start:end})}});out.push({start,end,state:$('availability').value});d.ranges=out.sort((a,b)=>a.start-b.start);resetEdit();persist();render();msg('Draft updated. Save via GitHub to share your changes.')};
async function refresh(){if(loading)return;loading=true;$('refresh').disabled=true;msg('Loading shared schedules…');try{let issues=[];for(let page=1;page<=20;page++){let res=await fetch(`https://api.github.com/repos/${REPO}/issues?state=all&per_page=100&sort=created&direction=asc&page=${page}`);if(!res.ok)throw new Error(res.status===403?'GitHub read limit reached. Try again in a few minutes.':'Could not load schedules. Try Refresh.');let batch=await res.json();issues.push(...batch);if(batch.length<100)break;if(page===20)throw new Error('Schedule history too large. Contact the repository owner.')}
 let next=Array.from({length:4},()=>({name:'',ranges:[],owner:''}));for(const issue of issues){if(issue.pull_request)continue;let match=(issue.body||'').match(/<!-- team-time-ranges-v1\s+([\s\S]*?)\s+-->/);if(!match)continue;try{let d=JSON.parse(match[1]);if(!Number.isInteger(d.member)||d.member<0||d.member>3||typeof d.name!=='string'||!d.name.trim()||!Array.isArray(d.ranges)||d.ranges.length>500||!d.ranges.every(r=>Number.isSafeInteger(r.start)&&Number.isSafeInteger(r.end)&&r.end>r.start&&Math.abs(r.start)<8e15&&Math.abs(r.end)<8e15&&labels[r.state]))continue;let r=next[d.member];if(r.owner&&r.owner!==issue.user.login)continue;next[d.member]={name:d.name.slice(0,32),ranges:d.ranges,owner:issue.user.login}}catch{}}
 records=next;for(let i=0;i<4;i++)if(drafts[i]&&JSON.stringify(drafts[i].ranges)===JSON.stringify(records[i].ranges)&&drafts[i].name===records[i].name)delete drafts[i];persist();render();msg('Shared schedules loaded. '+(Object.keys(drafts).length?'You have unsaved drafts.':'Choose your calendar and add your times.'));
 }catch(e){msg(e.message)}finally{loading=false;$('refresh').disabled=false}}
$('member').onchange=()=>{selected=Number($('member').value);resetEdit();persist();render()};$('name').oninput=()=>{draft().name=$('name').value;persist()};function changeZone(z){zone=z;$('timezone').value=zone;resetEdit();$('start').value='';$('end').value='';persist();render();msg('All calendars are shown in '+zone)}$('timezone').onchange=()=>changeZone($('timezone').value);$('local').onclick=()=>changeZone(Intl.DateTimeFormat().resolvedOptions().timeZone);
$('prev').onclick=()=>{monday=dateAt(-7);render()};$('next').onclick=()=>{monday=dateAt(7);render()};$('today').onclick=()=>{monday=currentMonday();render()};$('refresh').onclick=refresh;$('undo').onclick=()=>{delete drafts[selected];resetEdit();persist();render();msg('Local draft discarded.')};
$('save').onclick=()=>{let d=draft();d.name=$('name').value.trim();if(!d.name){$('name').focus();msg('Enter your name before saving.');return}d.ranges=d.ranges.filter(r=>r.end>Date.now()-35*86400000);persist();let body=`Availability for ${d.name} (calendar ${selected+1}).\n\nSubmit this issue to share your schedule, then return to the planner and click Refresh.\n\n<!-- team-time-ranges-v1\n${JSON.stringify({member:selected,name:d.name,ranges:d.ranges})}\n-->`,url=`https://github.com/${REPO}/issues/new?title=${encodeURIComponent('Availability · '+d.name)}&body=${encodeURIComponent(body)}`;if(url.length>28000){msg('Too many ranges to share. Remove some ranges and try again.');return}window.open(url,'_blank','noopener');msg('On GitHub, click Create, then return and Refresh. Use '+(records[selected].owner?'@'+records[selected].owner:'your own GitHub account')+'.')};
monday=currentMonday();$('start').value=dateAt(0).toISOString().slice(0,10)+'T09:00';$('end').value=dateAt(0).toISOString().slice(0,10)+'T17:00';render();refresh();
