'use strict';
const REPO='abrahamalcuin/team-call-planner',KEY='team-time-weekly-v1',$=id=>document.getElementById(id),labels={free:'Free',maybe:'Maybe',busy:'Unavailable'},DAY=86400000,WEEK=7*DAY,MIN=60000,days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
let prefs={};try{prefs=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
let zone=prefs.zone||Intl.DateTimeFormat().resolvedOptions().timeZone,selected=Number(prefs.member)||0,editorId=prefs.editorId||crypto.randomUUID(),drafts={},records=Array.from({length:4},()=>({name:'',ranges:[],owner:'',editorId:''})),monday,loaded=false,loading=false,editIndex=null;
function parts(t,tz=zone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(t)).map(p=>[p.type,p.value]))}
function local(t,tz=zone){const p=parts(t,tz);return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
function instant(v,tz=zone){if(!v)return NaN;let guess=Date.parse(v+'Z'),t=guess;if(!Number.isFinite(t))return NaN;for(let n=0;n<4;n++)t+=guess-Date.parse(local(t,tz)+':00Z');return local(t,tz)===v?t:NaN}
function mondayFor(t,tz=zone){let d=new Date(local(t,tz).slice(0,10)+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d}
function dateAt(n){return new Date(+monday+n*DAY)}
function weekly(ranges,tz=zone){let out=[];for(const r of ranges){let a=new Date(local(r.start,tz)+'Z'),b=new Date(local(r.end,tz)+'Z'),start=((a.getUTCDay()+6)%7)*1440+a.getUTCHours()*60+a.getUTCMinutes(),duration=(b-a)/MIN;if(duration<=0)continue;if(duration>=10080){out.push({start:0,end:10080,state:r.state});continue}let end=start+duration;out.push({start,end:Math.min(end,10080),state:r.state});if(end>10080)out.push({start:0,end:end-10080,state:r.state})}return {timezone:tz,weekly:out.sort((a,b)=>a.start-b.start)}}
function project(data){let out=[],base=mondayFor(+monday+3*DAY,data.timezone),viewStart=instant(monday.toISOString().slice(0,16)),viewEnd=instant(dateAt(7).toISOString().slice(0,16));for(let shift=-1;shift<=1;shift++)for(const r of data.weekly){let a=new Date(+base+shift*WEEK+r.start*MIN),b=new Date(+base+shift*WEEK+r.end*MIN),start=instant(a.toISOString().slice(0,16),data.timezone),end=instant(b.toISOString().slice(0,16),data.timezone);if(Number.isFinite(start)&&Number.isFinite(end)&&end>start&&end>viewStart&&start<viewEnd)out.push({start:Math.max(start,viewStart),end:Math.min(end,viewEnd),state:r.state})}return out.sort((a,b)=>a.start-b.start)}
function persist(){let saved={};for(const [i,d] of Object.entries(drafts))saved[i]={name:d.name,...weekly(d.ranges)};localStorage.setItem(KEY,JSON.stringify({zone,member:selected,editorId,drafts:saved}))}
function canEdit(i=selected){return loaded&&!!records[i].owner&&records[i].editorId===editorId}
function own(i){return canEdit(i)&&drafts[i]?drafts[i]:records[i]}
function draft(){if(!canEdit())throw new Error('This calendar is locked.');return drafts[selected]||(drafts[selected]={name:records[selected].name,ranges:records[selected].ranges.map(r=>({...r}))})}
function msg(s){$('status').textContent=s}
function element(tag,cls,text){let e=document.createElement(tag);e.className=cls||'';if(text)e.textContent=text;return e}
function resetEdit(){editIndex=null}
function describe(r){const f=t=>new Intl.DateTimeFormat('en',{weekday:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:zone}).format(new Date(t));return f(r.start)+' → '+f(r.end)}
function edit(r,index){if(!canEdit())return;editIndex=index;$('rangeTime').textContent=describe(r);$('rangeColor').value=r.state;$('rangeDialog').showModal()}
const zones=Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):['Asia/Manila','America/New_York','America/Los_Angeles','Europe/London'];for(const z of new Set(['UTC',zone,...zones]))$('timezone').add(new Option(z.replaceAll('_',' '),z));$('timezone').value=zone;$('member').value=selected;
function render(){
const unlocked=canEdit(),r=records[selected];$('name').value=own(selected).name||'';$('name').disabled=!loaded||!!r.owner&&!unlocked;$('save').disabled=!loaded||!!r.owner&&!unlocked;$('save').textContent=!r.owner?'Claim this calendar via GitHub ↗':unlocked?'Save via GitHub ↗':'Claimed by @'+r.owner;$('undo').disabled=!unlocked;$('availability').disabled=!unlocked;$('restore').hidden=!loaded||!r.owner||unlocked;
for(let i=0;i<4;i++)$('member').options[i].textContent=(own(i).name||`Person ${i+1}`)+(records[i].owner?(canEdit(i)?' · yours':' · locked'):' · unclaimed');
const root=$('calendars'),scrolls=[...root.querySelectorAll('.scroll')].map(x=>[x.scrollTop,x.scrollLeft]);root.replaceChildren();for(let i=0;i<4;i++){
let active=i===selected&&canEdit(i),card=element('section','card'+(active?' editing':'')),head=element('div','card-head'),person=element('div','person');person.append(element('span','avatar',String(i+1)),document.createTextNode(own(i).name||`Person ${i+1}`),element('span','meta',records[i].owner?'@'+records[i].owner:'Unclaimed calendar'));let badge=element('button','badge',!loaded?'Loading…':!records[i].owner?'Claim calendar':canEdit(i)?(active?'Editing':'Edit my calendar'):'🔒 Claimed');badge.disabled=!loaded||!!records[i].owner&&!canEdit(i);badge.onclick=()=>{selected=i;$('member').value=i;render();if(!records[i].owner)$('name').focus()};head.append(person,badge);card.append(head);let sc=element('div','scroll'),grid=element('div','timeline');grid.append(element('div','corner','Time'));for(const day of days)grid.append(element('div','day',day));let axis=element('div','axis');for(let h=0;h<24;h++){let t=element('span','',String(h).padStart(2,'0')+':00');t.style.top=h*36+'px';axis.append(t)}grid.append(axis);
for(let day=0;day<7;day++){let col=element('div','day-column'),start=instant(dateAt(day).toISOString().slice(0,16)),end=instant(dateAt(day+1).toISOString().slice(0,16));own(i).ranges.forEach((range,index)=>{if(range.end<=start||range.start>=end)return;let a=Math.max(start,range.start),b=Math.min(end,range.end),pa=parts(a),pb=parts(b),top=a===start?0:Number(pa.hour)*60+Number(pa.minute),bottom=b===end?1440:Number(pb.hour)*60+Number(pb.minute);if(bottom<=top)bottom=top+Math.max(1,(b-a)/MIN);let block=element('button','range '+range.state,labels[range.state]+' '+pa.hour+':'+pa.minute+'–'+(b===end?'24:00':pb.hour+':'+pb.minute));block.style.top=top/60*36+'px';block.style.height=Math.max(4,(bottom-top)/60*36)+'px';block.disabled=!active;block.title=labels[range.state]+' · '+describe(range)+' '+zone;block.setAttribute('aria-label',block.title);block.onclick=()=>edit(range,index);col.append(block)});grid.append(col)}sc.append(grid);card.append(sc);root.append(card);sc.scrollTop=scrolls[i]?.[0]??252;sc.scrollLeft=scrolls[i]?.[1]??0}
let list=$('rangeList');list.replaceChildren();own(selected).ranges.forEach((r,index)=>{let row=element('div','range-row'),button=element('button','','Edit');button.disabled=!unlocked;button.onclick=()=>edit(r,index);row.append(element('span','dot '+r.state),element('span','',labels[r.state]+' · '+describe(r)),button);list.append(row)});
}
function valid(d){try{return Number.isInteger(d.member)&&d.member>=0&&d.member<4&&typeof d.name==='string'&&d.name.trim()&&typeof d.editorId==='string'&&/^[a-zA-Z0-9-]{20,80}$/.test(d.editorId)&&typeof d.timezone==='string'&&!!new Intl.DateTimeFormat('en',{timeZone:d.timezone})&&Array.isArray(d.weekly)&&d.weekly.length<=500&&d.weekly.every(r=>Number.isInteger(r.start)&&Number.isInteger(r.end)&&r.start>=0&&r.end<=10080&&r.end>r.start&&['free','maybe','busy'].includes(r.state))}catch{return false}}
function reduceIssues(issues){let next=Array.from({length:4},()=>({name:'',ranges:[],owner:'',editorId:''}));for(const issue of issues){if(issue.pull_request)continue;const match=(issue.body||'').match(/<!-- team-time-weekly-v1\s+([\s\S]*?)\s+-->/);if(!match)continue;try{const d=JSON.parse(match[1]);if(!valid(d))continue;let old=next[d.member];if(old.owner&&old.owner!==issue.user.login)continue;if(d.action==='restore'){if(!old.owner)continue;next[d.member]={...old,editorId:d.editorId};continue}next[d.member]={...d,name:d.name.slice(0,32),owner:issue.user.login,ranges:project(d)}}catch{}}return next}
async function refresh(){if(loading)return;loading=true;$('refresh').disabled=true;msg('Loading shared calendars…');try{let issues=[];for(let page=1;page<=20;page++){let res=await fetch(`https://api.github.com/repos/${REPO}/issues?state=all&per_page=100&sort=created&direction=asc&page=${page}`);if(!res.ok)throw new Error('Could not load calendars. Please try Refresh again shortly.');let batch=await res.json();issues.push(...batch);if(batch.length<100)break;if(page===20)throw new Error('Calendar history is too large. Contact the repository owner.')}if(typeof gesture!=='undefined'&&gesture)finishGesture(true);records=reduceIssues(issues);loaded=true;for(let i=0;i<4;i++)if(drafts[i]&&!canEdit(i))delete drafts[i];persist();render();msg('Choose an unclaimed calendar, or edit your own. Claimed calendars are locked to their GitHub owner.')}catch(e){msg(e.message)}finally{loading=false;$('refresh').disabled=false}}
function submit(action){const r=records[selected];if(!loaded)return;if(action==='save'&&r.owner&&!canEdit())return;let name=($('name').value||r.name).trim();if(!name){$('name').focus();msg('Enter your name to claim this calendar.');return}let d={member:selected,name,editorId,action,...(action==='restore'?{timezone:r.timezone,weekly:r.weekly}:weekly(own(selected).ranges))};let body=`${action==='restore'?'Restore editing access':'Weekly availability'} for ${name}.\n\nSubmit this issue, then return to the planner and refresh. ${r.owner?'Only @'+r.owner+' can update this calendar.':'The first GitHub author to submit a claim owns this calendar.'}\n\n<!-- team-time-weekly-v1\n${JSON.stringify(d)}\n-->`;let url=`https://github.com/${REPO}/issues/new?title=${encodeURIComponent((action==='restore'?'Restore · ':r.owner?'Availability · ':'Claim calendar · ')+name)}&body=${encodeURIComponent(body)}`;if(url.length>28000){msg('Too many ranges to share. Remove some ranges first.');return}window.open(url,'_blank','noopener');msg('Complete the issue on GitHub, then return and Refresh. '+(r.owner?'Sign in as @'+r.owner+'.':''))}
$('member').onchange=()=>{selected=Number($('member').value);resetEdit();persist();render()};$('name').oninput=()=>{if(canEdit()){draft().name=$('name').value;persist()}};$('save').onclick=()=>submit('save');$('restore').onclick=()=>submit('restore');$('refresh').onclick=refresh;$('undo').onclick=()=>{delete drafts[selected];persist();render();msg('Local draft discarded.')};
function changeZone(z){const snapshots=Object.fromEntries(Object.entries(drafts).map(([i,d])=>[i,{name:d.name,...weekly(d.ranges)}]));zone=z;monday=mondayFor(Date.now());$('timezone').value=zone;for(const r of records)if(r.owner)r.ranges=project(r);for(const [i,d] of Object.entries(snapshots))drafts[i]={name:d.name,ranges:project(d)};persist();render();msg('Showing Monday–Sunday in '+zone)}$('timezone').onchange=()=>changeZone($('timezone').value);$('local').onclick=()=>changeZone(Intl.DateTimeFormat().resolvedOptions().timeZone);
$('updateRange').onclick=()=>{if(canEdit()&&editIndex!==null){draft().ranges[editIndex].state=$('rangeColor').value;persist();render()}$('rangeDialog').close();resetEdit()};$('removeRange').onclick=()=>{if(canEdit()&&editIndex!==null){draft().ranges.splice(editIndex,1);persist();render()}$('rangeDialog').close();resetEdit()};
monday=mondayFor(Date.now());for(const [i,d] of Object.entries(prefs.drafts||{})){try{drafts[i]={name:d.name,ranges:project(d)}}catch{}}persist();render();refresh();
